MAPPING = {
    'U+00A9': {'name': 'COPYRIGHT SIGN'},
    'U+00AE': {'name': 'REGISTERED SIGN'},
    'U+1F004': {'name': 'MAHJONG TILE RED DRAGON'},
    'U+1F0CF': {'name': 'PLAYING CARD BLACK JOKER'},
    'U+1F170': {'name': 'NEGATIVE SQUARED LATIN CAPITAL LETTER A'},
    'U+1F171': {'name': 'NEGATIVE SQUARED LATIN CAPITAL LETTER B'},
    'U+1F17E': {'name': 'NEGATIVE SQUARED LATIN CAPITAL LETTER O'},
    'U+1F17F': {'name': 'NEGATIVE SQUARED LATIN CAPITAL LETTER P'},
    'U+1F18E': {'name': 'NEGATIVE SQUARED AB'},
    'U+1F191': {'name': 'SQUARED CL'},
    'U+1F192': {'name': 'SQUARED COOL'},
    'U+1F193': {'name': 'SQUARED FREE'},
    'U+1F194': {'name': 'SQUARED ID'},
    'U+1F195': {'name': 'SQUARED NEW'},
    'U+1F196': {'name': 'SQUARED NG'},
    'U+1F197': {'name': 'SQUARED OK'},
    'U+1F198': {'name': 'SQUARED SOS'},
    'U+1F199': {'name': 'SQUARED UP WITH EXCLAMATION MARK'},
    'U+1F19A': {'name': 'SQUARED VS'},
    'U+1F201': {'name': 'SQUARED KATAKANA KOKO'},
    'U+1F202': {'name': 'SQUARED KATAKANA SA'},
    'U+1F21A': {'name': 'SQUARED CJK UNIFIED IDEOGRAPH-7121'},
    'U+1F22F': {'name': 'SQUARED CJK UNIFIED IDEOGRAPH-6307'},
    'U+1F232': {'name': 'SQUARED CJK UNIFIED IDEOGRAPH-7981'},
    'U+1F233': {'name': 'SQUARED CJK UNIFIED IDEOGRAPH-7A7A'},
    'U+1F234': {'name': 'SQUARED CJK UNIFIED IDEOGRAPH-5408'},
    'U+1F235': {'name': 'SQUARED CJK UNIFIED IDEOGRAPH-6E80'},
    'U+1F236': {'name': 'SQUARED CJK UNIFIED IDEOGRAPH-6709'},
    'U+1F237': {'name': 'SQUARED CJK UNIFIED IDEOGRAPH-6708'},
    'U+1F238': {'name': 'SQUARED CJK UNIFIED IDEOGRAPH-7533'},
    'U+1F239': {'name': 'SQUARED CJK UNIFIED IDEOGRAPH-5272'},
    'U+1F23A': {'name': 'SQUARED CJK UNIFIED IDEOGRAPH-55B6'},
    'U+1F250': {'name': 'CIRCLED IDEOGRAPH ADVANTAGE'},
    'U+1F251': {'name': 'CIRCLED IDEOGRAPH ACCEPT'},
    'U+1F300': {'name': 'CYCLONE'},
    'U+1F301': {'name': 'FOGGY'},
    'U+1F302': {'name': 'CLOSED UMBRELLA'},
    'U+1F303': {'name': 'NIGHT WITH STARS'},
    'U+1F304': {'name': 'SUNRISE OVER MOUNTAINS'},
    'U+1F305': {'name': 'SUNRISE'},
    'U+1F306': {'name': 'CITYSCAPE AT DUSK'},
    'U+1F307': {'name': 'SUNSET OVER BUILDINGS'},
    'U+1F308': {'name': 'RAINBOW'},
    'U+1F309': {'name': 'BRIDGE AT NIGHT'},
    'U+1F30A': {'name': 'WATER WAVE'},
    'U+1F30B': {'name': 'VOLCANO'},
    'U+1F30C': {'name': 'MILKY WAY'},
    'U+1F30F': {'name': 'EARTH GLOBE ASIA-AUSTRALIA'},
    'U+1F311': {'name': 'NEW MOON SYMBOL'},
    'U+1F313': {'name': 'FIRST QUARTER MOON SYMBOL'},
    'U+1F314': {'name': 'WAXING GIBBOUS MOON SYMBOL'},
    'U+1F315': {'name': 'FULL MOON SYMBOL'},
    'U+1F319': {'name': 'CRESCENT MOON'},
    'U+1F31B': {'name': 'FIRST QUARTER MOON WITH FACE'},
    'U+1F31F': {'name': 'GLOWING STAR'},
    'U+1F320': {'name': 'SHOOTING STAR'},
    'U+1F330': {'name': 'CHESTNUT'},
    'U+1F331': {'name': 'SEEDLING'},
    'U+1F334': {'name': 'PALM TREE'},
    'U+1F335': {'name': 'CACTUS'},
    'U+1F337': {'name': 'TULIP'},
    'U+1F338': {'name': 'CHERRY BLOSSOM'},
    'U+1F339': {'name': 'ROSE'},
    'U+1F33A': {'name': 'HIBISCUS'},
    'U+1F33B': {'name': 'SUNFLOWER'},
    'U+1F33C': {'name': 'BLOSSOM'},
    'U+1F33D': {'name': 'EAR OF MAIZE'},
    'U+1F33E': {'name': 'EAR OF RICE'},
    'U+1F33F': {'name': 'HERB'},
    'U+1F340': {'name': 'FOUR LEAF CLOVER'},
    'U+1F341': {'name': 'MAPLE LEAF'},
    'U+1F342': {'name': 'FALLEN LEAF'},
    'U+1F343': {'name': 'LEAF FLUTTERING IN WIND'},
    'U+1F344': {'name': 'MUSHROOM'},
    'U+1F345': {'name': 'TOMATO'},
    'U+1F346': {'name': 'AUBERGINE'},
    'U+1F347': {'name': 'GRAPES'},
    'U+1F348': {'name': 'MELON'},
    'U+1F349': {'name': 'WATERMELON'},
    'U+1F34A': {'name': 'TANGERINE'},
    'U+1F34C': {'name': 'BANANA'},
    'U+1F34D': {'name': 'PINEAPPLE'},
    'U+1F34E': {'name': 'RED APPLE'},
    'U+1F34F': {'name': 'GREEN APPLE'},
    'U+1F351': {'name': 'PEACH'},
    'U+1F352': {'name': 'CHERRIES'},
    'U+1F353': {'name': 'STRAWBERRY'},
    'U+1F354': {'name': 'HAMBURGER'},
    'U+1F355': {'name': 'SLICE OF PIZZA'},
    'U+1F356': {'name': 'MEAT ON BONE'},
    'U+1F357': {'name': 'POULTRY LEG'},
    'U+1F358': {'name': 'RICE CRACKER'},
    'U+1F359': {'name': 'RICE BALL'},
    'U+1F35A': {'name': 'COOKED RICE'},
    'U+1F35B': {'name': 'CURRY AND RICE'},
    'U+1F35C': {'name': 'STEAMING BOWL'},
    'U+1F35D': {'name': 'SPAGHETTI'},
    'U+1F35E': {'name': 'BREAD'},
    'U+1F35F': {'name': 'FRENCH FRIES'},
    'U+1F360': {'name': 'ROASTED SWEET POTATO'},
    'U+1F361': {'name': 'DANGO'},
    'U+1F362': {'name': 'ODEN'},
    'U+1F363': {'name': 'SUSHI'},
    'U+1F364': {'name': 'FRIED SHRIMP'},
    'U+1F365': {'name': 'FISH CAKE WITH SWIRL DESIGN'},
    'U+1F366': {'name': 'SOFT ICE CREAM'},
    'U+1F367': {'name': 'SHAVED ICE'},
    'U+1F368': {'name': 'ICE CREAM'},
    'U+1F369': {'name': 'DOUGHNUT'},
    'U+1F36A': {'name': 'COOKIE'},
    'U+1F36B': {'name': 'CHOCOLATE BAR'},
    'U+1F36C': {'name': 'CANDY'},
    'U+1F36D': {'name': 'LOLLIPOP'},
    'U+1F36E': {'name': 'CUSTARD'},
    'U+1F36F': {'name': 'HONEY POT'},
    'U+1F370': {'name': 'SHORTCAKE'},
    'U+1F371': {'name': 'BENTO BOX'},
    'U+1F372': {'name': 'POT OF FOOD'},
    'U+1F373': {'name': 'COOKING'},
    'U+1F374': {'name': 'FORK AND KNIFE'},
    'U+1F375': {'name': 'TEACUP WITHOUT HANDLE'},
    'U+1F376': {'name': 'SAKE BOTTLE AND CUP'},
    'U+1F377': {'name': 'WINE GLASS'},
    'U+1F378': {'name': 'COCKTAIL GLASS'},
    'U+1F379': {'name': 'TROPICAL DRINK'},
    'U+1F37A': {'name': 'BEER MUG'},
    'U+1F37B': {'name': 'CLINKING BEER MUGS'},
    'U+1F380': {'name': 'RIBBON'},
    'U+1F381': {'name': 'WRAPPED PRESENT'},
    'U+1F382': {'name': 'BIRTHDAY CAKE'},
    'U+1F383': {'name': 'JACK-O-LANTERN'},
    'U+1F384': {'name': 'CHRISTMAS TREE'},
    'U+1F385': {'name': 'FATHER CHRISTMAS'},
    'U+1F386': {'name': 'FIREWORKS'},
    'U+1F387': {'name': 'FIREWORK SPARKLER'},
    'U+1F388': {'name': 'BALLOON'},
    'U+1F389': {'name': 'PARTY POPPER'},
    'U+1F38A': {'name': 'CONFETTI BALL'},
    'U+1F38B': {'name': 'TANABATA TREE'},
    'U+1F38C': {'name': 'CROSSED FLAGS'},
    'U+1F38D': {'name': 'PINE DECORATION'},
    'U+1F38E': {'name': 'JAPANESE DOLLS'},
    'U+1F38F': {'name': 'CARP STREAMER'},
    'U+1F390': {'name': 'WIND CHIME'},
    'U+1F391': {'name': 'MOON VIEWING CEREMONY'},
    'U+1F392': {'name': 'SCHOOL SATCHEL'},
    'U+1F393': {'name': 'GRADUATION CAP'},
    'U+1F3A0': {'name': 'CAROUSEL HORSE'},
    'U+1F3A1': {'name': 'FERRIS WHEEL'},
    'U+1F3A2': {'name': 'ROLLER COASTER'},
    'U+1F3A3': {'name': 'FISHING POLE AND FISH'},
    'U+1F3A4': {'name': 'MICROPHONE'},
    'U+1F3A5': {'name': 'MOVIE CAMERA'},
    'U+1F3A6': {'name': 'CINEMA'},
    'U+1F3A7': {'name': 'HEADPHONE'},
    'U+1F3A8': {'name': 'ARTIST PALETTE'},
    'U+1F3A9': {'name': 'TOP HAT'},
    'U+1F3AA': {'name': 'CIRCUS TENT'},
    'U+1F3AB': {'name': 'TICKET'},
    'U+1F3AC': {'name': 'CLAPPER BOARD'},
    'U+1F3AD': {'name': 'PERFORMING ARTS'},
    'U+1F3AE': {'name': 'VIDEO GAME'},
    'U+1F3AF': {'name': 'DIRECT HIT'},
    'U+1F3B0': {'name': 'SLOT MACHINE'},
    'U+1F3B1': {'name': 'BILLIARDS'},
    'U+1F3B2': {'name': 'GAME DIE'},
    'U+1F3B3': {'name': 'BOWLING'},
    'U+1F3B4': {'name': 'FLOWER PLAYING CARDS'},
    'U+1F3B5': {'name': 'MUSICAL NOTE'},
    'U+1F3B6': {'name': 'MULTIPLE MUSICAL NOTES'},
    'U+1F3B7': {'name': 'SAXOPHONE'},
    'U+1F3B8': {'name': 'GUITAR'},
    'U+1F3B9': {'name': 'MUSICAL KEYBOARD'},
    'U+1F3BA': {'name': 'TRUMPET'},
    'U+1F3BB': {'name': 'VIOLIN'},
    'U+1F3BC': {'name': 'MUSICAL SCORE'},
    'U+1F3BD': {'name': 'RUNNING SHIRT WITH SASH'},
    'U+1F3BE': {'name': 'TENNIS RACQUET AND BALL'},
    'U+1F3BF': {'name': 'SKI AND SKI BOOT'},
    'U+1F3C0': {'name': 'BASKETBALL AND HOOP'},
    'U+1F3C1': {'name': 'CHEQUERED FLAG'},
    'U+1F3C2': {'name': 'SNOWBOARDER'},
    'U+1F3C3': {'name': 'RUNNER'},
    'U+1F3C4': {'name': 'SURFER'},
    'U+1F3C6': {'name': 'TROPHY'},
    'U+1F3C8': {'name': 'AMERICAN FOOTBALL'},
    'U+1F3CA': {'name': 'SWIMMER'},
    'U+1F3E0': {'name': 'HOUSE BUILDING'},
    'U+1F3E1': {'name': 'HOUSE WITH GARDEN'},
    'U+1F3E2': {'name': 'OFFICE BUILDING'},
    'U+1F3E3': {'name': 'JAPANESE POST OFFICE'},
    'U+1F3E5': {'name': 'HOSPITAL'},
    'U+1F3E6': {'name': 'BANK'},
    'U+1F3E7': {'name': 'AUTOMATED TELLER MACHINE'},
    'U+1F3E8': {'name': 'HOTEL'},
    'U+1F3E9': {'name': 'LOVE HOTEL'},
    'U+1F3EA': {'name': 'CONVENIENCE STORE'},
    'U+1F3EB': {'name': 'SCHOOL'},
    'U+1F3EC': {'name': 'DEPARTMENT STORE'},
    'U+1F3ED': {'name': 'FACTORY'},
    'U+1F3EE': {'name': 'IZAKAYA LANTERN'},
    'U+1F3EF': {'name': 'JAPANESE CASTLE'},
    'U+1F3F0': {'name': 'EUROPEAN CASTLE'},
    'U+1F40C': {'name': 'SNAIL'},
    'U+1F40D': {'name': 'SNAKE'},
    'U+1F40E': {'name': 'HORSE'},
    'U+1F411': {'name': 'SHEEP'},
    'U+1F412': {'name': 'MONKEY'},
    'U+1F414': {'name': 'CHICKEN'},
    'U+1F417': {'name': 'BOAR'},
    'U+1F418': {'name': 'ELEPHANT'},
    'U+1F419': {'name': 'OCTOPUS'},
    'U+1F41A': {'name': 'SPIRAL SHELL'},
    'U+1F41B': {'name': 'BUG'},
    'U+1F41C': {'name': 'ANT'},
    'U+1F41D': {'name': 'HONEYBEE'},
    'U+1F41E': {'name': 'LADY BEETLE'},
    'U+1F41F': {'name': 'FISH'},
    'U+1F420': {'name': 'TROPICAL FISH'},
    'U+1F421': {'name': 'BLOWFISH'},
    'U+1F422': {'name': 'TURTLE'},
    'U+1F423': {'name': 'HATCHING CHICK'},
    'U+1F424': {'name': 'BABY CHICK'},
    'U+1F425': {'name': 'FRONT-FACING BABY CHICK'},
    'U+1F426': {'name': 'BIRD'},
    'U+1F427': {'name': 'PENGUIN'},
    'U+1F428': {'name': 'KOALA'},
    'U+1F429': {'name': 'POODLE'},
    'U+1F42B': {'name': 'BACTRIAN CAMEL'},
    'U+1F42C': {'name': 'DOLPHIN'},
    'U+1F42D': {'name': 'MOUSE FACE'},
    'U+1F42E': {'name': 'COW FACE'},
    'U+1F42F': {'name': 'TIGER FACE'},
    'U+1F430': {'name': 'RABBIT FACE'},
    'U+1F431': {'name': 'CAT FACE'},
    'U+1F432': {'name': 'DRAGON FACE'},
    'U+1F433': {'name': 'SPOUTING WHALE'},
    'U+1F434': {'name': 'HORSE FACE'},
    'U+1F435': {'name': 'MONKEY FACE'},
    'U+1F436': {'name': 'DOG FACE'},
    'U+1F437': {'name': 'PIG FACE'},
    'U+1F438': {'name': 'FROG FACE'},
    'U+1F439': {'name': 'HAMSTER FACE'},
    'U+1F43A': {'name': 'WOLF FACE'},
    'U+1F43B': {'name': 'BEAR FACE'},
    'U+1F43C': {'name': 'PANDA FACE'},
    'U+1F43D': {'name': 'PIG NOSE'},
    'U+1F43E': {'name': 'PAW PRINTS'},
    'U+1F440': {'name': 'EYES'},
    'U+1F442': {'name': 'EAR'},
    'U+1F443': {'name': 'NOSE'},
    'U+1F444': {'name': 'MOUTH'},
    'U+1F445': {'name': 'TONGUE'},
    'U+1F446': {'name': 'WHITE UP POINTING BACKHAND INDEX'},
    'U+1F447': {'name': 'WHITE DOWN POINTING BACKHAND INDEX'},
    'U+1F448': {'name': 'WHITE LEFT POINTING BACKHAND INDEX'},
    'U+1F449': {'name': 'WHITE RIGHT POINTING BACKHAND INDEX'},
    'U+1F44A': {'name': 'FISTED HAND SIGN'},
    'U+1F44B': {'name': 'WAVING HAND SIGN'},
    'U+1F44C': {'name': 'OK HAND SIGN'},
    'U+1F44D': {'name': 'THUMBS UP SIGN'},
    'U+1F44E': {'name': 'THUMBS DOWN SIGN'},
    'U+1F44F': {'name': 'CLAPPING HANDS SIGN'},
    'U+1F450': {'name': 'OPEN HANDS SIGN'},
    'U+1F451': {'name': 'CROWN'},
    'U+1F452': {'name': 'WOMANS HAT'},
    'U+1F453': {'name': 'EYEGLASSES'},
    'U+1F454': {'name': 'NECKTIE'},
    'U+1F455': {'name': 'T-SHIRT'},
    'U+1F456': {'name': 'JEANS'},
    'U+1F457': {'name': 'DRESS'},
    'U+1F458': {'name': 'KIMONO'},
    'U+1F459': {'name': 'BIKINI'},
    'U+1F45A': {'name': 'WOMANS CLOTHES'},
    'U+1F45B': {'name': 'PURSE'},
    'U+1F45C': {'name': 'HANDBAG'},
    'U+1F45D': {'name': 'POUCH'},
    'U+1F45E': {'name': 'MANS SHOE'},
    'U+1F45F': {'name': 'ATHLETIC SHOE'},
    'U+1F460': {'name': 'HIGH-HEELED SHOE'},
    'U+1F461': {'name': 'WOMANS SANDAL'},
    'U+1F462': {'name': 'WOMANS BOOTS'},
    'U+1F463': {'name': 'FOOTPRINTS'},
    'U+1F464': {'name': 'BUST IN SILHOUETTE'},
    'U+1F466': {'name': 'BOY'},
    'U+1F467': {'name': 'GIRL'},
    'U+1F468': {'name': 'MAN'},
    'U+1F469': {'name': 'WOMAN'},
    'U+1F46A': {'name': 'FAMILY'},
    'U+1F46B': {'name': 'MAN AND WOMAN HOLDING HANDS'},
    'U+1F46E': {'name': 'POLICE OFFICER'},
    'U+1F46F': {'name': 'WOMAN WITH BUNNY EARS'},
    'U+1F470': {'name': 'BRIDE WITH VEIL'},
    'U+1F471': {'name': 'PERSON WITH BLOND HAIR'},
    'U+1F472': {'name': 'MAN WITH GUA PI MAO'},
    'U+1F473': {'name': 'MAN WITH TURBAN'},
    'U+1F474': {'name': 'OLDER MAN'},
    'U+1F475': {'name': 'OLDER WOMAN'},
    'U+1F476': {'name': 'BABY'},
    'U+1F477': {'name': 'CONSTRUCTION WORKER'},
    'U+1F478': {'name': 'PRINCESS'},
    'U+1F479': {'name': 'JAPANESE OGRE'},
    'U+1F47A': {'name': 'JAPANESE GOBLIN'},
    'U+1F47B': {'name': 'GHOST'},
    'U+1F47C': {'name': 'BABY ANGEL'},
    'U+1F47D': {'name': 'EXTRATERRESTRIAL ALIEN'},
    'U+1F47E': {'name': 'ALIEN MONSTER'},
    'U+1F47F': {'name': 'IMP'},
    'U+1F480': {'name': 'SKULL'},
    'U+1F481': {'name': 'INFORMATION DESK PERSON'},
    'U+1F482': {'name': 'GUARDSMAN'},
    'U+1F483': {'name': 'DANCER'},
    'U+1F484': {'name': 'LIPSTICK'},
    'U+1F485': {'name': 'NAIL POLISH'},
    'U+1F486': {'name': 'FACE MASSAGE'},
    'U+1F487': {'name': 'HAIRCUT'},
    'U+1F488': {'name': 'BARBER POLE'},
    'U+1F489': {'name': 'SYRINGE'},
    'U+1F48A': {'name': 'PILL'},
    'U+1F48B': {'name': 'KISS MARK'},
    'U+1F48C': {'name': 'LOVE LETTER'},
    'U+1F48D': {'name': 'RING'},
    'U+1F48E': {'name': 'GEM STONE'},
    'U+1F48F': {'name': 'KISS'},
    'U+1F490': {'name': 'BOUQUET'},
    'U+1F491': {'name': 'COUPLE WITH HEART'},
    'U+1F492': {'name': 'WEDDING'},
    'U+1F493': {'name': 'BEATING HEART'},
    'U+1F494': {'name': 'BROKEN HEART'},
    'U+1F495': {'name': 'TWO HEARTS'},
    'U+1F496': {'name': 'SPARKLING HEART'},
    'U+1F497': {'name': 'GROWING HEART'},
    'U+1F498': {'name': 'HEART WITH ARROW'},
    'U+1F499': {'name': 'BLUE HEART'},
    'U+1F49A': {'name': 'GREEN HEART'},
    'U+1F49B': {'name': 'YELLOW HEART'},
    'U+1F49C': {'name': 'PURPLE HEART'},
    'U+1F49D': {'name': 'HEART WITH RIBBON'},
    'U+1F49E': {'name': 'REVOLVING HEARTS'},
    'U+1F49F': {'name': 'HEART DECORATION'},
    'U+1F4A0': {'name': 'DIAMOND SHAPE WITH A DOT INSIDE'},
    'U+1F4A1': {'name': 'ELECTRIC LIGHT BULB'},
    'U+1F4A2': {'name': 'ANGER SYMBOL'},
    'U+1F4A3': {'name': 'BOMB'},
    'U+1F4A4': {'name': 'SLEEPING SYMBOL'},
    'U+1F4A5': {'name': 'COLLISION SYMBOL'},
    'U+1F4A6': {'name': 'SPLASHING SWEAT SYMBOL'},
    'U+1F4A7': {'name': 'DROPLET'},
    'U+1F4A8': {'name': 'DASH SYMBOL'},
    'U+1F4A9': {'name': 'PILE OF POO'},
    'U+1F4AA': {'name': 'FLEXED BICEPS'},
    'U+1F4AB': {'name': 'DIZZY SYMBOL'},
    'U+1F4AC': {'name': 'SPEECH BALLOON'},
    'U+1F4AE': {'name': 'WHITE FLOWER'},
    'U+1F4AF': {'name': 'HUNDRED POINTS SYMBOL'},
    'U+1F4B0': {'name': 'MONEY BAG'},
    'U+1F4B1': {'name': 'CURRENCY EXCHANGE'},
    'U+1F4B2': {'name': 'HEAVY DOLLAR SIGN'},
    'U+1F4B3': {'name': 'CREDIT CARD'},
    'U+1F4B4': {'name': 'BANKNOTE WITH YEN SIGN'},
    'U+1F4B5': {'name': 'BANKNOTE WITH DOLLAR SIGN'},
    'U+1F4B8': {'name': 'MONEY WITH WINGS'},
    'U+1F4B9': {'name': 'CHART WITH UPWARDS TREND AND YEN SIGN'},
    'U+1F4BA': {'name': 'SEAT'},
    'U+1F4BB': {'name': 'PERSONAL COMPUTER'},
    'U+1F4BC': {'name': 'BRIEFCASE'},
    'U+1F4BD': {'name': 'MINIDISC'},
    'U+1F4BE': {'name': 'FLOPPY DISK'},
    'U+1F4BF': {'name': 'OPTICAL DISC'},
    'U+1F4C0': {'name': 'DVD'},
    'U+1F4C1': {'name': 'FILE FOLDER'},
    'U+1F4C2': {'name': 'OPEN FILE FOLDER'},
    'U+1F4C3': {'name': 'PAGE WITH CURL'},
    'U+1F4C4': {'name': 'PAGE FACING UP'},
    'U+1F4C5': {'name': 'CALENDAR'},
    'U+1F4C6': {'name': 'TEAR-OFF CALENDAR'},
    'U+1F4C7': {'name': 'CARD INDEX'},
    'U+1F4C8': {'name': 'CHART WITH UPWARDS TREND'},
    'U+1F4C9': {'name': 'CHART WITH DOWNWARDS TREND'},
    'U+1F4CA': {'name': 'BAR CHART'},
    'U+1F4CB': {'name': 'CLIPBOARD'},
    'U+1F4CC': {'name': 'PUSHPIN'},
    'U+1F4CD': {'name': 'ROUND PUSHPIN'},
    'U+1F4CE': {'name': 'PAPERCLIP'},
    'U+1F4CF': {'name': 'STRAIGHT RULER'},
    'U+1F4D0': {'name': 'TRIANGULAR RULER'},
    'U+1F4D1': {'name': 'BOOKMARK TABS'},
    'U+1F4D2': {'name': 'LEDGER'},
    'U+1F4D3': {'name': 'NOTEBOOK'},
    'U+1F4D4': {'name': 'NOTEBOOK WITH DECORATIVE COVER'},
    'U+1F4D5': {'name': 'CLOSED BOOK'},
    'U+1F4D6': {'name': 'OPEN BOOK'},
    'U+1F4D7': {'name': 'GREEN BOOK'},
    'U+1F4D8': {'name': 'BLUE BOOK'},
    'U+1F4D9': {'name': 'ORANGE BOOK'},
    'U+1F4DA': {'name': 'BOOKS'},
    'U+1F4DB': {'name': 'NAME BADGE'},
    'U+1F4DC': {'name': 'SCROLL'},
    'U+1F4DD': {'name': 'MEMO'},
    'U+1F4DE': {'name': 'TELEPHONE RECEIVER'},
    'U+1F4DF': {'name': 'PAGER'},
    'U+1F4E0': {'name': 'FAX MACHINE'},
    'U+1F4E1': {'name': 'SATELLITE ANTENNA'},
    'U+1F4E2': {'name': 'PUBLIC ADDRESS LOUDSPEAKER'},
    'U+1F4E3': {'name': 'CHEERING MEGAPHONE'},
    'U+1F4E4': {'name': 'OUTBOX TRAY'},
    'U+1F4E5': {'name': 'INBOX TRAY'},
    'U+1F4E6': {'name': 'PACKAGE'},
    'U+1F4E7': {'name': 'E-MAIL SYMBOL'},
    'U+1F4E8': {'name': 'INCOMING ENVELOPE'},
    'U+1F4E9': {'name': 'ENVELOPE WITH DOWNWARDS ARROW ABOVE'},
    'U+1F4EA': {'name': 'CLOSED MAILBOX WITH LOWERED FLAG'},
    'U+1F4EB': {'name': 'CLOSED MAILBOX WITH RAISED FLAG'},
    'U+1F4EE': {'name': 'POSTBOX'},
    'U+1F4F0': {'name': 'NEWSPAPER'},
    'U+1F4F1': {'name': 'MOBILE PHONE'},
    'U+1F4F2': {'name': 'MOBILE PHONE WITH RIGHTWARDS ARROW AT LEFT'},
    'U+1F4F3': {'name': 'VIBRATION MODE'},
    'U+1F4F4': {'name': 'MOBILE PHONE OFF'},
    'U+1F4F6': {'name': 'ANTENNA WITH BARS'},
    'U+1F4F7': {'name': 'CAMERA'},
    'U+1F4F9': {'name': 'VIDEO CAMERA'},
    'U+1F4FA': {'name': 'TELEVISION'},
    'U+1F4FB': {'name': 'RADIO'},
    'U+1F4FC': {'name': 'VIDEOCASSETTE'},
    'U+1F503': {'name': 'CLOCKWISE DOWNWARDS AND UPWARDS OPEN CIRCLE ARROWS'},
    'U+1F50A': {'name': 'SPEAKER WITH THREE SOUND WAVES'},
    'U+1F50B': {'name': 'BATTERY'},
    'U+1F50C': {'name': 'ELECTRIC PLUG'},
    'U+1F50D': {'name': 'LEFT-POINTING MAGNIFYING GLASS'},
    'U+1F50E': {'name': 'RIGHT-POINTING MAGNIFYING GLASS'},
    'U+1F50F': {'name': 'LOCK WITH INK PEN'},
    'U+1F510': {'name': 'CLOSED LOCK WITH KEY'},
    'U+1F511': {'name': 'KEY'},
    'U+1F512': {'name': 'LOCK'},
    'U+1F513': {'name': 'OPEN LOCK'},
    'U+1F514': {'name': 'BELL'},
    'U+1F516': {'name': 'BOOKMARK'},
    'U+1F517': {'name': 'LINK SYMBOL'},
    'U+1F518': {'name': 'RADIO BUTTON'},
    'U+1F519': {'name': 'BACK WITH LEFTWARDS ARROW ABOVE'},
    'U+1F51A': {'name': 'END WITH LEFTWARDS ARROW ABOVE'},
    'U+1F51B': {'name': 'ON WITH EXCLAMATION MARK WITH LEFT RIGHT ARROW ABOVE'},
    'U+1F51C': {'name': 'SOON WITH RIGHTWARDS ARROW ABOVE'},
    'U+1F51D': {'name': 'TOP WITH UPWARDS ARROW ABOVE'},
    'U+1F51E': {'name': 'NO ONE UNDER EIGHTEEN SYMBOL'},
    'U+1F51F': {'name': 'KEYCAP TEN'},
    'U+1F520': {'name': 'INPUT SYMBOL FOR LATIN CAPITAL LETTERS'},
    'U+1F521': {'name': 'INPUT SYMBOL FOR LATIN SMALL LETTERS'},
    'U+1F522': {'name': 'INPUT SYMBOL FOR NUMBERS'},
    'U+1F523': {'name': 'INPUT SYMBOL FOR SYMBOLS'},
    'U+1F524': {'name': 'INPUT SYMBOL FOR LATIN LETTERS'},
    'U+1F525': {'name': 'FIRE'},
    'U+1F526': {'name': 'ELECTRIC TORCH'},
    'U+1F527': {'name': 'WRENCH'},
    'U+1F528': {'name': 'HAMMER'},
    'U+1F529': {'name': 'NUT AND BOLT'},
    'U+1F52A': {'name': 'HOCHO'},
    'U+1F52B': {'name': 'PISTOL'},
    'U+1F52E': {'name': 'CRYSTAL BALL'},
    'U+1F52F': {'name': 'SIX POINTED STAR WITH MIDDLE DOT'},
    'U+1F530': {'name': 'JAPANESE SYMBOL FOR BEGINNER'},
    'U+1F531': {'name': 'TRIDENT EMBLEM'},
    'U+1F532': {'name': 'BLACK SQUARE BUTTON'},
    'U+1F533': {'name': 'WHITE SQUARE BUTTON'},
    'U+1F534': {'name': 'LARGE RED CIRCLE'},
    'U+1F535': {'name': 'LARGE BLUE CIRCLE'},
    'U+1F536': {'name': 'LARGE ORANGE DIAMOND'},
    'U+1F537': {'name': 'LARGE BLUE DIAMOND'},
    'U+1F538': {'name': 'SMALL ORANGE DIAMOND'},
    'U+1F539': {'name': 'SMALL BLUE DIAMOND'},
    'U+1F53A': {'name': 'UP-POINTING RED TRIANGLE'},
    'U+1F53B': {'name': 'DOWN-POINTING RED TRIANGLE'},
    'U+1F53C': {'name': 'UP-POINTING SMALL RED TRIANGLE'},
    'U+1F53D': {'name': 'DOWN-POINTING SMALL RED TRIANGLE'},
    'U+1F550': {'name': 'CLOCK FACE ONE OCLOCK'},
    'U+1F551': {'name': 'CLOCK FACE TWO OCLOCK'},
    'U+1F552': {'name': 'CLOCK FACE THREE OCLOCK'},
    'U+1F553': {'name': 'CLOCK FACE FOUR OCLOCK'},
    'U+1F554': {'name': 'CLOCK FACE FIVE OCLOCK'},
    'U+1F555': {'name': 'CLOCK FACE SIX OCLOCK'},
    'U+1F556': {'name': 'CLOCK FACE SEVEN OCLOCK'},
    'U+1F557': {'name': 'CLOCK FACE EIGHT OCLOCK'},
    'U+1F558': {'name': 'CLOCK FACE NINE OCLOCK'},
    'U+1F559': {'name': 'CLOCK FACE TEN OCLOCK'},
    'U+1F55A': {'name': 'CLOCK FACE ELEVEN OCLOCK'},
    'U+1F55B': {'name': 'CLOCK FACE TWELVE OCLOCK'},
    'U+1F5FB': {'name': 'MOUNT FUJI'},
    'U+1F5FC': {'name': 'TOKYO TOWER'},
    'U+1F5FD': {'name': 'STATUE OF LIBERTY'},
    'U+1F5FE': {'name': 'SILHOUETTE OF JAPAN'},
    'U+1F5FF': {'name': 'MOYAI'},
    'U+1F601': {'name': 'GRINNING FACE WITH SMILING EYES'},
    'U+1F602': {'name': 'FACE WITH TEARS OF JOY'},
    'U+1F603': {'name': 'SMILING FACE WITH OPEN MOUTH'},
    'U+1F604': {'name': 'SMILING FACE WITH OPEN MOUTH AND SMILING EYES'},
    'U+1F605': {'name': 'SMILING FACE WITH OPEN MOUTH AND COLD SWEAT'},
    'U+1F606': {'name': 'SMILING FACE WITH OPEN MOUTH AND TIGHTLY-CLOSED EYES'},
    'U+1F609': {'name': 'WINKING FACE'},
    'U+1F60A': {'name': 'SMILING FACE WITH SMILING EYES'},
    'U+1F60B': {'name': 'FACE SAVOURING DELICIOUS FOOD'},
    'U+1F60C': {'name': 'RELIEVED FACE'},
    'U+1F60D': {'name': 'SMILING FACE WITH HEART-SHAPED EYES'},
    'U+1F60F': {'name': 'SMIRKING FACE'},
    'U+1F612': {'name': 'UNAMUSED FACE'},
    'U+1F613': {'name': 'FACE WITH COLD SWEAT'},
    'U+1F614': {'name': 'PENSIVE FACE'},
    'U+1F616': {'name': 'CONFOUNDED FACE'},
    'U+1F618': {'name': 'FACE THROWING A KISS'},
    'U+1F61A': {'name': 'KISSING FACE WITH CLOSED EYES'},
    'U+1F61C': {'name': 'FACE WITH STUCK-OUT TONGUE AND WINKING EYE'},
    'U+1F61D': {'name': 'FACE WITH STUCK-OUT TONGUE AND TIGHTLY-CLOSED EYES'},
    'U+1F61E': {'name': 'DISAPPOINTED FACE'},
    'U+1F620': {'name': 'ANGRY FACE'},
    'U+1F621': {'name': 'POUTING FACE'},
    'U+1F622': {'name': 'CRYING FACE'},
    'U+1F623': {'name': 'PERSEVERING FACE'},
    'U+1F624': {'name': 'FACE WITH LOOK OF TRIUMPH'},
    'U+1F625': {'name': 'DISAPPOINTED BUT RELIEVED FACE'},
    'U+1F628': {'name': 'FEARFUL FACE'},
    'U+1F629': {'name': 'WEARY FACE'},
    'U+1F62A': {'name': 'SLEEPY FACE'},
    'U+1F62B': {'name': 'TIRED FACE'},
    'U+1F62D': {'name': 'LOUDLY CRYING FACE'},
    'U+1F630': {'name': 'FACE WITH OPEN MOUTH AND COLD SWEAT'},
    'U+1F631': {'name': 'FACE SCREAMING IN FEAR'},
    'U+1F632': {'name': 'ASTONISHED FACE'},
    'U+1F633': {'name': 'FLUSHED FACE'},
    'U+1F635': {'name': 'DIZZY FACE'},
    'U+1F637': {'name': 'FACE WITH MEDICAL MASK'},
    'U+1F638': {'name': 'GRINNING CAT FACE WITH SMILING EYES'},
    'U+1F639': {'name': 'CAT FACE WITH TEARS OF JOY'},
    'U+1F63A': {'name': 'SMILING CAT FACE WITH OPEN MOUTH'},
    'U+1F63B': {'name': 'SMILING CAT FACE WITH HEART-SHAPED EYES'},
    'U+1F63C': {'name': 'CAT FACE WITH WRY SMILE'},
    'U+1F63D': {'name': 'KISSING CAT FACE WITH CLOSED EYES'},
    'U+1F63E': {'name': 'POUTING CAT FACE'},
    'U+1F63F': {'name': 'CRYING CAT FACE'},
    'U+1F640': {'name': 'WEARY CAT FACE'},
    'U+1F645': {'name': 'FACE WITH NO GOOD GESTURE'},
    'U+1F646': {'name': 'FACE WITH OK GESTURE'},
    'U+1F647': {'name': 'PERSON BOWING DEEPLY'},
    'U+1F648': {'name': 'SEE-NO-EVIL MONKEY'},
    'U+1F649': {'name': 'HEAR-NO-EVIL MONKEY'},
    'U+1F64A': {'name': 'SPEAK-NO-EVIL MONKEY'},
    'U+1F64B': {'name': 'HAPPY PERSON RAISING ONE HAND'},
    'U+1F64C': {'name': 'PERSON RAISING BOTH HANDS IN CELEBRATION'},
    'U+1F64D': {'name': 'PERSON FROWNING'},
    'U+1F64E': {'name': 'PERSON WITH POUTING FACE'},
    'U+1F64F': {'name': 'PERSON WITH FOLDED HANDS'},
    'U+1F680': {'name': 'ROCKET'},
    'U+1F683': {'name': 'RAILWAY CAR'},
    'U+1F684': {'name': 'HIGH-SPEED TRAIN'},
    'U+1F685': {'name': 'HIGH-SPEED TRAIN WITH BULLET NOSE'},
    'U+1F687': {'name': 'METRO'},
    'U+1F689': {'name': 'STATION'},
    'U+1F68C': {'name': 'BUS'},
    'U+1F68F': {'name': 'BUS STOP'},
    'U+1F691': {'name': 'AMBULANCE'},
    'U+1F692': {'name': 'FIRE ENGINE'},
    'U+1F693': {'name': 'POLICE CAR'},
    'U+1F695': {'name': 'TAXI'},
    'U+1F697': {'name': 'AUTOMOBILE'},
    'U+1F699': {'name': 'RECREATIONAL VEHICLE'},
    'U+1F69A': {'name': 'DELIVERY TRUCK'},
    'U+1F6A2': {'name': 'SHIP'},
    'U+1F6A4': {'name': 'SPEEDBOAT'},
    'U+1F6A5': {'name': 'HORIZONTAL TRAFFIC LIGHT'},
    'U+1F6A7': {'name': 'CONSTRUCTION SIGN'},
    'U+1F6A8': {'name': 'POLICE CARS REVOLVING LIGHT'},
    'U+1F6A9': {'name': 'TRIANGULAR FLAG ON POST'},
    'U+1F6AA': {'name': 'DOOR'},
    'U+1F6AB': {'name': 'NO ENTRY SIGN'},
    'U+1F6AC': {'name': 'SMOKING SYMBOL'},
    'U+1F6AD': {'name': 'NO SMOKING SYMBOL'},
    'U+1F6B2': {'name': 'BICYCLE'},
    'U+1F6B6': {'name': 'PEDESTRIAN'},
    'U+1F6B9': {'name': 'MENS SYMBOL'},
    'U+1F6BA': {'name': 'WOMENS SYMBOL'},
    'U+1F6BB': {'name': 'RESTROOM'},
    'U+1F6BC': {'name': 'BABY SYMBOL'},
    'U+1F6BD': {'name': 'TOILET'},
    'U+1F6BE': {'name': 'WATER CLOSET'},
    'U+1F6C0': {'name': 'BATH'},
    'U+2002': {'name': 'EN SPACE'},
    'U+2003': {'name': 'EM SPACE'},
    'U+2005': {'name': 'FOUR-PER-EM SPACE'},
    'U+203C': {'name': 'DOUBLE EXCLAMATION MARK'},
    'U+2049': {'name': 'EXCLAMATION QUESTION MARK'},
    'U+2122': {'name': 'TRADE MARK SIGN'},
    'U+2139': {'name': 'INFORMATION SOURCE'},
    'U+2194': {'name': 'LEFT RIGHT ARROW'},
    'U+2195': {'name': 'UP DOWN ARROW'},
    'U+2196': {'name': 'NORTH WEST ARROW'},
    'U+2197': {'name': 'NORTH EAST ARROW'},
    'U+2198': {'name': 'SOUTH EAST ARROW'},
    'U+2199': {'name': 'SOUTH WEST ARROW'},
    'U+21A9': {'name': 'LEFTWARDS ARROW WITH HOOK'},
    'U+21AA': {'name': 'RIGHTWARDS ARROW WITH HOOK'},
    'U+231A': {'name': 'WATCH'},
    'U+231B': {'name': 'HOURGLASS'},
    'U+23E9': {'name': 'BLACK RIGHT-POINTING DOUBLE TRIANGLE'},
    'U+23EA': {'name': 'BLACK LEFT-POINTING DOUBLE TRIANGLE'},
    'U+23EB': {'name': 'BLACK UP-POINTING DOUBLE TRIANGLE'},
    'U+23EC': {'name': 'BLACK DOWN-POINTING DOUBLE TRIANGLE'},
    'U+23F0': {'name': 'ALARM CLOCK'},
    'U+23F3': {'name': 'HOURGLASS WITH FLOWING SAND'},
    'U+24C2': {'name': 'CIRCLED LATIN CAPITAL LETTER M'},
    'U+25AA': {'name': 'BLACK SMALL SQUARE'},
    'U+25AB': {'name': 'WHITE SMALL SQUARE'},
    'U+25B6': {'name': 'BLACK RIGHT-POINTING TRIANGLE'},
    'U+25C0': {'name': 'BLACK LEFT-POINTING TRIANGLE'},
    'U+25FB': {'name': 'WHITE MEDIUM SQUARE'},
    'U+25FC': {'name': 'BLACK MEDIUM SQUARE'},
    'U+25FD': {'name': 'WHITE MEDIUM SMALL SQUARE'},
    'U+25FE': {'name': 'BLACK MEDIUM SMALL SQUARE'},
    'U+2600': {'name': 'BLACK SUN WITH RAYS'},
    'U+2601': {'name': 'CLOUD'},
    'U+260E': {'name': 'BLACK TELEPHONE'},
    'U+2611': {'name': 'BALLOT BOX WITH CHECK'},
    'U+2614': {'name': 'UMBRELLA WITH RAIN DROPS'},
    'U+2615': {'name': 'HOT BEVERAGE'},
    'U+261D': {'name': 'WHITE UP POINTING INDEX'},
    'U+263A': {'name': 'WHITE SMILING FACE'},
    'U+2648': {'name': 'ARIES'},
    'U+2649': {'name': 'TAURUS'},
    'U+264A': {'name': 'GEMINI'},
    'U+264B': {'name': 'CANCER'},
    'U+264C': {'name': 'LEO'},
    'U+264D': {'name': 'VIRGO'},
    'U+264E': {'name': 'LIBRA'},
    'U+264F': {'name': 'SCORPIUS'},
    'U+2650': {'name': 'SAGITTARIUS'},
    'U+2651': {'name': 'CAPRICORN'},
    'U+2652': {'name': 'AQUARIUS'},
    'U+2653': {'name': 'PISCES'},
    'U+2660': {'name': 'BLACK SPADE SUIT'},
    'U+2663': {'name': 'BLACK CLUB SUIT'},
    'U+2665': {'name': 'BLACK HEART SUIT'},
    'U+2666': {'name': 'BLACK DIAMOND SUIT'},
    'U+2668': {'name': 'HOT SPRINGS'},
    'U+267B': {'name': 'BLACK UNIVERSAL RECYCLING SYMBOL'},
    'U+267F': {'name': 'WHEELCHAIR SYMBOL'},
    'U+2693': {'name': 'ANCHOR'},
    'U+26A0': {'name': 'WARNING SIGN'},
    'U+26A1': {'name': 'HIGH VOLTAGE SIGN'},
    'U+26AA': {'name': 'MEDIUM WHITE CIRCLE'},
    'U+26AB': {'name': 'MEDIUM BLACK CIRCLE'},
    'U+26BD': {'name': 'SOCCER BALL'},
    'U+26BE': {'name': 'BASEBALL'},
    'U+26C4': {'name': 'SNOWMAN WITHOUT SNOW'},
    'U+26C5': {'name': 'SUN BEHIND CLOUD'},
    'U+26CE': {'name': 'OPHIUCHUS'},
    'U+26D4': {'name': 'NO ENTRY'},
    'U+26EA': {'name': 'CHURCH'},
    'U+26F2': {'name': 'FOUNTAIN'},
    'U+26F3': {'name': 'FLAG IN HOLE'},
    'U+26F5': {'name': 'SAILBOAT'},
    'U+26FA': {'name': 'TENT'},
    'U+26FD': {'name': 'FUEL PUMP'},
    'U+2702': {'name': 'BLACK SCISSORS'},
    'U+2705': {'name': 'WHITE HEAVY CHECK MARK'},
    'U+2708': {'name': 'AIRPLANE'},
    'U+2709': {'name': 'ENVELOPE'},
    'U+270A': {'name': 'RAISED FIST'},
    'U+270B': {'name': 'RAISED HAND'},
    'U+270C': {'name': 'VICTORY HAND'},
    'U+270F': {'name': 'PENCIL'},
    'U+2712': {'name': 'BLACK NIB'},
    'U+2714': {'name': 'HEAVY CHECK MARK'},
    'U+2716': {'name': 'HEAVY MULTIPLICATION X'},
    'U+2728': {'name': 'SPARKLES'},
    'U+2733': {'name': 'EIGHT SPOKED ASTERISK'},
    'U+2734': {'name': 'EIGHT POINTED BLACK STAR'},
    'U+2744': {'name': 'SNOWFLAKE'},
    'U+2747': {'name': 'SPARKLE'},
    'U+274C': {'name': 'CROSS MARK'},
    'U+274E': {'name': 'NEGATIVE SQUARED CROSS MARK'},
    'U+2753': {'name': 'BLACK QUESTION MARK ORNAMENT'},
    'U+2754': {'name': 'WHITE QUESTION MARK ORNAMENT'},
    'U+2755': {'name': 'WHITE EXCLAMATION MARK ORNAMENT'},
    'U+2757': {'name': 'HEAVY EXCLAMATION MARK SYMBOL'},
    'U+2764': {'name': 'HEAVY BLACK HEART'},
    'U+2795': {'name': 'HEAVY PLUS SIGN'},
    'U+2796': {'name': 'HEAVY MINUS SIGN'},
    'U+2797': {'name': 'HEAVY DIVISION SIGN'},
    'U+27A1': {'name': 'BLACK RIGHTWARDS ARROW'},
    'U+27B0': {'name': 'CURLY LOOP'},
    'U+2934': {'name': 'ARROW POINTING RIGHTWARDS THEN CURVING UPWARDS'},
    'U+2935': {'name': 'ARROW POINTING RIGHTWARDS THEN CURVING DOWNWARDS'},
    'U+2B05': {'name': 'LEFTWARDS BLACK ARROW'},
    'U+2B06': {'name': 'UPWARDS BLACK ARROW'},
    'U+2B07': {'name': 'DOWNWARDS BLACK ARROW'},
    'U+2B1B': {'name': 'BLACK LARGE SQUARE'},
    'U+2B1C': {'name': 'WHITE LARGE SQUARE'},
    'U+2B50': {'name': 'WHITE MEDIUM STAR'},
    'U+2B55': {'name': 'HEAVY LARGE CIRCLE'},
    'U+3030': {'name': 'WAVY DASH'},
    'U+303D': {'name': 'PART ALTERNATION MARK'},
    'U+3297': {'name': 'CIRCLED IDEOGRAPH CONGRATULATION'},
    'U+3299': {'name': 'CIRCLED IDEOGRAPH SECRET'}
}
